#!/bin/bash

# Environment
. ./environment.sh

oc new-project ${PROJECT_NAME}

. ./deploy-database.sh
. ./deploy-rest-goals.sh
. ./deploy-rest-users.sh
. ./deploy-rest-advice.sh
. ./deploy-frontend.sh
